kenya_econ_dbt:
  target: prod
  outputs:
    prod:
      type: bigquery
      method: oauth
      project: "{{ env_var('GCP_PROJECT_ID', 'kenya-econ-dev') }}"
      dataset: staging
      location: "{{ env_var('BQ_LOCATION', 'africa-south1') }}"
      threads: 4
      priority: interactive
      job_execution_timeout_seconds: 300
      scopes:
        - https://www.googleapis.com/auth/bigquery
        - https://www.googleapis.com/auth/cloud-platform
